[[mounts]]
source = "./"
destination = "/var/www/html"
mode = "copy"

[nginx]
# Definir o diretório raiz do servidor Nginx
root = "/var/www/html"

# Configuração para a reescrita
location / {
    try_files $uri $uri/ /index.php$is_args$args;
}

# Configuração para o arquivo index.php como DirectoryIndex
index index.php;
