[[mounts]]
source = "./"
destination = "/var/www/html"
mode = "copy"

[nginx]
# Definir o diretório raiz do servidor Nginx
root = "/var/www/html"

# Configuração para o arquivo index.php como DirectoryIndex
index = "index.php"

# Configuração para a reescrita
http_server_block = '''
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
'''
