<?php require __DIR__ . '/components/layout/header.phtml';?>

<div class="container d-flex align-items-center justify-content-center" style="height:100vh;">
  <div class="row">
    <div class="col-md-12 text-center" style="position:relative;bottom:10rem;">
      <h1 class="text-dark">404</h1>
      <h3 class="text-secondary">Página não encontrada :(</h3>
    </div>
  </div>
</div>

<?php require __DIR__ . '/components/layout/footer.phtml';?>